apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-microservice
  namespace: {{ .Values.namespace }}
  labels:
    app: lab-microservice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: lab-microservice
  template:
    metadata:
      labels:
        app: lab-microservice
    spec:
      containers:
        - name: lab-microservice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "{{ .Values.env.aspnetcoreEnvironment }}"
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
