apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-microservice
  namespace: {{ .Release.Namespace }}
  labels:
    app: lab-microservice

spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: lab-microservice

  template:
    metadata:
      labels:
        app: lab-microservice
    spec:
      containers:
        - name: lab-microservice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}

          ports:
            - containerPort: {{ .Values.service.targetPort | default 8080 }}

          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ .Values.env.aspnetcoreEnvironment | default "Production" | quote }}

          resources:
{{- toYaml .Values.resources | nindent 12 }}
