apiVersion: v1
kind: Service
metadata:
  name: lab-orders-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: lab-orders-service
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: lab-orders-service
  ports:
    - name: http
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
{{- if eq (.Values.service.type | default "ClusterIP") "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
