apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-microservice
  namespace: argocd
spec:
  project: default

  destination:
    namespace: lab
    server: https://kubernetes.default.svc

  source:
    repoURL: https://github.com/yuzelt/argocd_yuzelt.git
    targetRevision: main
    path: lab-microservice-chart
    helm:
      parameters:
        - name: namespace
          value: lab
        - name: image.repository
          value: taskin87/lab-microservice
        - name: image.tag
          value: v1.2.18
  72f3dda (chore: set lab-microservice image.tag to v1.2.15)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
