apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-orders-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/yuzelt/argocd_yuzelt.git
    targetRevision: main
    path: lab-orders-service-chart
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: lab

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
