apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2025-12-20T21:06:06Z"
  generation: 50
  name: lab-microservice
  namespace: argocd
  resourceVersion: "121275"
  uid: c5fc7887-5b6c-438c-a436-d8fba05d1f8e
spec:
  destination:
    namespace: lab
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: namespace
        value: lab
    path: lab-microservice-chart
    repoURL: https://github.com/yuzelt/argocd_yuzelt.git
    targetRevision: main
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    lastTransitionTime: "2025-12-21T17:45:16Z"
    status: Healthy
  history:
  - deployStartedAt: "2025-12-20T21:11:03Z"
    deployedAt: "2025-12-20T21:11:03Z"
    id: 0
    initiatedBy:
      automated: true
    revision: 6535d3bbd4a561fa018dfb421344fc37a1f12ce6
    source:
      helm:
        parameters:
        - name: namespace
          value: lab
      path: lab-microservice-chart
      repoURL: https://github.com/yuzelt/argocd_yuzelt.git
      targetRevision: main
  operationState:
    finishedAt: "2025-12-20T21:11:03Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        prune: true
        revision: 6535d3bbd4a561fa018dfb421344fc37a1f12ce6
        source:
          helm:
            parameters:
            - name: namespace
              value: lab
          path: lab-microservice-chart
          repoURL: https://github.com/yuzelt/argocd_yuzelt.git
          targetRevision: main
        syncOptions:
        - CreateNamespace=true
    phase: Succeeded
    startedAt: "2025-12-20T21:11:03Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/lab-microservice created
        name: lab-microservice
        namespace: lab
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        images:
        - taskin87/lab-microservice:v1.2.3
        kind: Deployment
        message: deployment.apps/lab-microservice created
        name: lab-microservice
        namespace: lab
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 6535d3bbd4a561fa018dfb421344fc37a1f12ce6
      source:
        helm:
          parameters:
          - name: namespace
            value: lab
        path: lab-microservice-chart
        repoURL: https://github.com/yuzelt/argocd_yuzelt.git
        targetRevision: main
  reconciledAt: "2025-12-21T18:17:16Z"
  resourceHealthSource: appTree
  resources:
  - kind: Service
    name: lab-microservice
    namespace: lab
    status: Synced
    version: v1
  - group: apps
    kind: Deployment
    name: lab-microservice
    namespace: lab
    status: Synced
    version: v1
  sourceHydrator: {}
  sourceType: Helm
  summary:
    images:
    - taskin87/lab-microservice:v1.2.3
  sync:
    comparedTo:
      destination:
        namespace: lab
        server: https://kubernetes.default.svc
      source:
        helm:
          parameters:
          - name: namespace
            value: lab
        path: lab-microservice-chart
        repoURL: https://github.com/yuzelt/argocd_yuzelt.git
        targetRevision: main
    revision: 6535d3bbd4a561fa018dfb421344fc37a1f12ce6
    status: Synced
